# Generated by Django 3.2.21 on 2023-12-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('projects', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='projects', to='tasks.Task'),
        ),
    ]
