# Generated by Django 3.2.21 on 2023-11-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblist',
            name='urls_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
