# Generated by Django 3.2.21 on 2023-12-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weblist', '0002_alter_weblist_urls_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblist',
            name='urls_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblists', to=settings.AUTH_USER_MODEL),
        ),
    ]
