# Generated by Django 3.2.21 on 2024-04-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
